name: Run Pester Tests

on:
  push:
    branches: [main]
    paths:
      - "**/*.ps1"
      - ".github/workflows/run-pester.yml"
  pull_request:
    branches: [main]
    paths:
      - "**/*.ps1"
      - ".github/workflows/run-pester.yml"

paths:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Pester Tests
        run: |
          Invoke-Pester ./tests -Output Detailed

        shell: pwsh
